site_name: PAULA Instrutora Virtual

repo_url: https://github.com/mdsreq-fga-unb/2022.1-Paula-Instrutora-Virtual

theme:
  name: material
  features: navigation.tabs
  logo: img/logo.png

extra_css:
  - style.css

nav:
  - Início:
    - Inicio: index.md
    - Visão do Produto e do Projeto: visaoProdutoProjeto.md
    - Resumo Sprints: resumo_sprints/sprints.md
    - Lições Aprendidas: licoes_aprendidas.md
    - Histórico de Reuniões: reunioes.md
  - Apresentações:
    - Unidade 1: apresentacoes/unidade_1.md
    - Unidade 2: apresentacoes/unidade_2.md
    - Unidade 3: apresentacoes/unidade_3.md
  - Entregas:
    - Unidade 1: entregas/unidade_1.md
    - Unidade 2: entregas/unidade_2.md
    - Unidade 3: entregas/unidade_3.md
  - MVPs: mvps.md
  - Lições Aprendidas: licoes_aprendidas.md
  - Sprints: sprints.md
  - Histórico de Reuniões: reunioes.md

markdown_extensions:
  - attr_list