site_name: PAULA Instrutora Virtual

theme:
  name: material
  logo: assets/logo.png
  language: pt
  extra_css: style.css

nav:
  - Início: index.md
  - Apresentações:
    - Apresentação da Unidade 1: apresentacoes/unidade_1.md
    - Apresentação da Unidade 2: apresentacoes/unidade_2.md
  - MVPs: mvps.md
  - Histórico de Reuniões: reunioes.md
  - Visão do Produto e do Projeto: visaoProdutoProjeto.md
