site_name: PAULA Instrutora Virtual

theme: 
  name: material
  logo: assets/logo.png
  language: pt
  extra_css: style.css

nav:
  - Início: index.md
  - Apresentações:
    - Apresentação da Unidade 1: apresentacoes/unidade_1.md
  - Visão do Produto e do Projeto: visaoProdutoProjeto.md
