site_name: PAULA Instrutora Virtual

theme:
  name: material
  logo: img/logo.png
  language: pt
  extra_css: docs/style.css

nav:
  - Início: index.md
  - Visão do Produto e do Projeto: visaoProdutoProjeto.md
  - Apresentações:
    - Unidade 1: apresentacoes/unidade_1.md
    - Unidade 2: apresentacoes/unidade_2.md
  - Entregas:
    - Unidade 1: entregas/unidade_1.md
    - Unidade 2: entregas/unidade_2.md
  - MVPs: mvps.md
  - Lições Aprendidas: licoes_aprendidas.md
  - Histórico de Reuniões: reunioes.md
